dist: xenial
sudo: required
language: python
  - "3.6"
virtualenv:
  system_site_packages: true
  
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
 - python3 --version
 - sudo apt-get update
 - sudo pip3 install --upgrade pip -i https://pypi.python.org/simple
 - pip3 install -r requirements.txt
script:
  - python3 ./src/zbrac/run.py 



