dist: xenial
sudo: required
language: python
  - "3.6"
virtualenv:
  system_site_packages: true
  
addons:
  apt:
    packages:
      - "python"
      - "python-pip"
install:
 - python --version
 - sudo apt-get update
 - sudo pip install --upgrade pip -i https://pypi.python.org/simple
 - pip install -r requirements.txt
script:
  - python ./src/zbrac/run.py 



