dist: xenial
sudo: required
language: python
  - "3.6"
virtualenv:
  system_site_packages: true
  
addons:
  apt:
    packages:
      - "python3.6"
      - "python3.6-pip"
install:
 - python3.6 --version
 - sudo apt-get update
 - sudo pip3.6 install --upgrade pip -i https://pypi.python.org/simple
 - pip3.6 install -r requirements.txt
script:
  - python3.6 ./src/zbrac/run.py 



